import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Link } from 'react-router-dom'

export interface MetricHelpContent {
  title: string
  metricKey: string
  subtitle: string
  whatIsIt: string
  howCalculated: string
  interpretation: string
  manualChapter: string
  formula?: string
}

export const METRIC_HELP_DATABASE: Record<string, MetricHelpContent> = {
  eal: {
    metricKey: 'eal',
    title: 'Expected Annual Loss (EAL)',
    subtitle: 'Primary quantitative baseline for annual financial risk',
    whatIsIt:
      'Expected Annual Loss (EAL) represents the statistical mean aggregate financial loss the enterprise expects to suffer over a one-year horizon across all threat events, asset vulnerabilities, and operational downtime.',
    howCalculated:
      'Modeled via 10,000 Monte Carlo simulation runs evaluating stochastic Loss Event Frequency (Poisson distribution) multiplied by compound Loss Magnitude (Log-Normal distributions covering primary revenue outage, incident response, PII record liabilities, and statutory penalties).',
    formula: 'EAL = \\sum_{i=1}^{N} (LEF_i \\times LM_i) = \\frac{1}{M} \\sum_{m=1}^{M} L_m',
    interpretation:
      'Use EAL as your executive security budget benchmark. Any security control portfolio is economically justifiable if its cost is lower than the projected reduction in EAL (net positive ROSI).',
    manualChapter: '/manual#eal',
  },
  var95: {
    metricKey: 'var95',
    title: 'P95 Value at Risk (1-in-20 Year Tail Event)',
    subtitle: 'High-severity extreme tail exposure threshold',
    whatIsIt:
      'P95 VaR represents the 95th percentile of the simulated annual loss distribution. In 95% of simulated years, enterprise losses will be below this threshold; in 5% of years (a 1-in-20 year catastrophic event), losses will exceed it.',
    howCalculated:
      'Empirically sampled from the sorted array of 10,000 annual aggregate losses generated by the Monte Carlo simulation engine at rank index 9,500.',
    formula: 'VaR_{0.95} = \\inf \\{ L \\in \\mathbb{R} : P(\\text{Loss} \\le L) \\ge 0.95 \\}',
    interpretation:
      'Used by CFOs and Risk Committees to size cyber insurance coverage limits and capital contingency reserves for severe security tail events.',
    manualChapter: '/manual#var',
  },
  var99: {
    metricKey: 'var99',
    title: 'P99 Value at Risk (1-in-100 Year Black Swan Event)',
    subtitle: 'Catastrophic systemic failure threshold',
    whatIsIt:
      'P99 VaR models catastrophic enterprise failure — systemic concurrent compromises such as simultaneous ransomware extortion across core banking switches and full database exfiltration.',
    howCalculated:
      'Empirically sampled from the 10,000 Monte Carlo run loss array at rank index 9,900.',
    formula: 'VaR_{0.99} = \\inf \\{ L \\in \\mathbb{R} : P(\\text{Loss} \\le L) \\ge 0.99 \\}',
    interpretation:
      'Critical for Board risk appetite governance and disaster recovery reserve planning under severe systemic stress tests.',
    manualChapter: '/manual#var',
  },
  regulatory: {
    metricKey: 'regulatory',
    title: 'Regulatory Fine Exposure',
    subtitle: 'Statutory exposure under RBI CSF, SEBI CSCRF & DPDPA 2023',
    whatIsIt:
      'Quantifies potential non-compliance penalties, regulatory audit sanctions, and mandatory reporting violation fines from statutory bodies (Reserve Bank of India, SEBI, and DPDP Act 2023) following data breach incidents.',
    howCalculated:
      'Derived from regulatory penalty schedules calibrated to customer record count, unpatched critical CVE duration, and compliance checklist gap severity scores.',
    formula: 'Exposure = \\text{Base Fine} + (Records \\times PenaltyRate) \\times GapMultiplier',
    interpretation:
      'Closing specific compliance control gaps directly eliminates this statutory exposure from your balance sheet.',
    manualChapter: '/manual#compliance',
  },
  rosi: {
    metricKey: 'rosi',
    title: 'Return on Security Investment (ROSI)',
    subtitle: 'Capital efficiency ratio for security spending',
    whatIsIt:
      'ROSI measures the financial productivity of allocating capital to a specific security control portfolio versus the baseline expected risk.',
    howCalculated:
      'Calculated as the Net Expected Risk Reduction (Baseline EAL minus Projected EAL) minus Control Cost, divided by Control Cost.',
    formula: 'ROSI = \\frac{(\\Delta EAL - \\text{Control Cost})}{\\text{Control Cost}} \\times 100\\%',
    interpretation:
      'A ROSI of +300% indicates that every ₹1 spent on security controls mitigates ₹4 in expected loss, generating ₹3 in net risk savings.',
    manualChapter: '/manual#investment',
  },
  knapsack: {
    metricKey: 'knapsack',
    title: 'MILP Knapsack Optimization',
    subtitle: 'Mathematical control selection under capital constraints',
    whatIsIt:
      'Mixed-Integer Linear Programming (MILP) solver that determines the optimal binary combination of security controls to deploy under a fixed capital budget ceiling.',
    howCalculated:
      'Maximizes total risk reduction \\(\\sum x_i \\Delta EAL_i\\) subject to \\(\\sum x_i Cost_i \\le Budget\\) with binary decision variables \\(x_i \\in \\{0, 1\\}\\).',
    formula: '\\max \\sum_{i=1}^{K} x_i \\Delta EAL_i \\quad \\text{s.t.} \\quad \\sum_{i=1}^{K} x_i C_i \\le \\text{Budget}',
    interpretation:
      'Eliminates arbitrary subjective security spending by proving mathematically which controls deliver the highest marginal return per rupee.',
    manualChapter: '/manual#investment',
  },
}

export function MetricInfoButton({
  metricKey,
  label,
  className = '',
}: {
  metricKey: keyof typeof METRIC_HELP_DATABASE
  label?: string
  className?: string
}) {
  const [isOpen, setIsOpen] = useState(false)
  const content = METRIC_HELP_DATABASE[metricKey]

  if (!content) return null

  return (
    <>
      <button
        type="button"
        className={`metric-info-trigger ${className}`}
        onClick={(e) => {
          e.stopPropagation()
          setIsOpen(true)
        }}
        title={`What is ${content.title}?`}
        aria-label={`Learn about ${content.title}`}
      >
        <span className="info-icon-char">ⓘ</span>
        {label && <span className="info-label-text">{label}</span>}
      </button>

      <AnimatePresence>
        {isOpen && (
          <div
            className="contextual-help-backdrop"
            onClick={() => setIsOpen(false)}
            role="dialog"
            aria-modal="true"
          >
            <motion.div
              className="contextual-help-card"
              initial={{ opacity: 0, x: 40, scale: 0.98 }}
              animate={{ opacity: 1, x: 0, scale: 1 }}
              exit={{ opacity: 0, x: 40, scale: 0.98 }}
              transition={{ duration: 0.22, ease: [0.22, 1, 0.36, 1] }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="help-header">
                <div>
                  <span className="help-overline">CRIQ METRIC BRIEF</span>
                  <h3 className="help-title">{content.title}</h3>
                  <p className="help-subtitle">{content.subtitle}</p>
                </div>
                <button
                  type="button"
                  className="help-close-btn"
                  onClick={() => setIsOpen(false)}
                  aria-label="Close metric information"
                >
                  ✕
                </button>
              </div>

              <div className="help-body">
                <div className="help-section">
                  <span className="help-section-tag">01 · DEFINITION</span>
                  <p className="help-text">{content.whatIsIt}</p>
                </div>

                <div className="help-section">
                  <span className="help-section-tag">02 · QUANTITATIVE CALCULATION</span>
                  <p className="help-text">{content.howCalculated}</p>
                  {content.formula && (
                    <div className="help-formula-box">
                      <code>{content.formula}</code>
                    </div>
                  )}
                </div>

                <div className="help-section">
                  <span className="help-section-tag">03 · EXECUTIVE INTERPRETATION</span>
                  <p className="help-text">{content.interpretation}</p>
                </div>
              </div>

              <div className="help-footer">
                <Link
                  to={content.manualChapter}
                  className="btn btn-primary btn-sm"
                  onClick={() => setIsOpen(false)}
                >
                  Read in User Manual →
                </Link>
                <button
                  type="button"
                  className="btn btn-ghost btn-sm"
                  onClick={() => setIsOpen(false)}
                >
                  Dismiss
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  )
}
